basePath: /api/v1
definitions:
  models.Car:
    properties:
      id:
        type: integer
      mark:
        type: string
      model:
        type: string
      owner:
        $ref: '#/definitions/models.Owner'
      regNum:
        type: string
      year:
        type: integer
    type: object
  models.Owner:
    properties:
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
host: localhost:8383
info:
  contact: {}
  title: Car Catalog API
  version: "1.0"
paths:
  /cars:
    get:
      consumes:
      - application/json
      description: get cars
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Car'
            type: array
      summary: List cars
      tags:
      - cars
swagger: "2.0"
